root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: true
  cliptimeout: 45
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  path: gpgcli-gitcli-fs+file:///home/lukasz/.password-store
  safecontent: false
  usesymbols: false
  notifications: false
mounts: {}
version: 1.7.0
