root:
  askformore: false
  autoimport: true
  autosync: true
  cliptimeout: 45
  noconfirm: false
  nopager: false
  path: /home/lukasz/.password-store
  safecontent: false
mounts: {}
version: 1.4.1
